
title: Bruce Zhang

# Theme settings
remote_theme: minima
plugins:
  - jekyll-remote-theme

# Additional configurations
baseurl: "/portfolio" # Adjust to your site's base URL if necessary
#url: "https://brucezhang1015.github.io" # Your site URL
